import re

with open('index.html', 'r', encoding='utf-8') as f:
    content = f.text if hasattr(f, 'text') else f.read()

# Define the comprehensive skill dictionaries for each sect & branch
skills_data = {
    'tldao': "[{name:'Vô Tướng Trảm',type:'DPS',priority:1,desc:'Đao chém trên ngựa 9x',level:'9x'},{name:'Dịch Cân Kinh',type:'Trấn Phái',priority:2,desc:'Tăng max sinh lực',level:'6x'},{name:'Thiếu Lâm Đao Pháp',type:'Cơ bản',priority:3,desc:'Kỹ năng đao cơ bản',level:'1x'},{name:'La Hán Trận',type:'Vòng sáng',priority:4,desc:'Phản đòn trận',level:'3x'},{name:'Bất Động Minh Vương',type:'Vòng sáng',priority:5,desc:'Tăng kháng tính',level:'1x'}]",
    'tlbong': "[{name:'Hoành Tảo Thiên Quân',type:'AoE',priority:1,desc:'Quét bổng diện rộng 9x',level:'9x'},{name:'Dịch Cân Kinh',type:'Trấn Phái',priority:2,desc:'Trấn phái tăng sinh lực',level:'6x'},{name:'Thiếu Lâm Bổng Pháp',type:'Cơ bản',priority:3,desc:'Bổng pháp nhập môn',level:'1x'},{name:'La Hán Trận',type:'Vòng sáng',priority:4,desc:'Phản đòn sát thương',level:'3x'},{name:'Sư Tử Hống',type:'Khống chế',priority:5,desc:'Gầm choáng diện rộng',level:'1x'}]",
    'tlquyen': "[{name:'Đạt Ma Độ Giang',type:'DPS',priority:1,desc:'Quyền 9x đấm choáng liên tục',level:'9x'},{name:'Dịch Cân Kinh',type:'Trấn Phái',priority:2,desc:'Trấn phái gia tăng thể lực',level:'6x'},{name:'Thiếu Lâm Quyền Pháp',type:'Cơ bản',priority:3,desc:'Quyền cơ bản',level:'1x'},{name:'La Hán Trận',type:'Vòng sáng',priority:4,desc:'Phản đòn cực gắt',level:'3x'},{name:'Nhữ Lai Thiên Diệp',type:'Tuyệt kỹ 5x',priority:5,desc:'Tuyệt kỹ trung cấp',level:'5x'}]",
    'tvchuy': "[{name:'Truy Tinh Trục Nguyệt',type:'DPS',priority:1,desc:'Chùy 9x Sát thương siêu khủng',level:'9x'},{name:'Thiên Vương Bản Nguyện',type:'Trấn Phái',priority:2,desc:'Trấn phái tăng sát thương',level:'6x'},{name:'Thiên Vương Chùy Pháp',type:'Cơ bản',priority:3,desc:'Chùy pháp nhập môn',level:'1x'},{name:'Tĩnh Tâm Quyết',type:'Hỗ trợ',priority:4,desc:'Tăng tốc độ xuất chiêu',level:'3x'},{name:'Huyết Chiến Cổ',type:'Vòng sáng',priority:5,desc:'Tăng tỷ lệ chí mạng',level:'3x'}]",
    'tvthuong': "[{name:'Huyết Chiến Bát Phương',type:'DPS',priority:1,desc:'Thương 9x đâm liên tục dồn sát thương',level:'9x'},{name:'Thiên Vương Bản Nguyện',type:'Trấn Phái',priority:2,desc:'Trấn phái tăng sát thương',level:'6x'},{name:'Thiên Vương Thương Pháp',type:'Cơ bản',priority:3,desc:'Đâm kiếm cơ bản',level:'1x'},{name:'Tĩnh Tâm Quyết',type:'Hỗ trợ',priority:4,desc:'Tăng tốc độ xuất chiêu',level:'3x'},{name:'Kim Chung Tráo',type:'Buff',priority:5,desc:'Tăng mọi loại kháng tính',level:'1x'}]",
    'tvdao': "[{name:'Phá Thiên Trảm',type:'DPS AoE',priority:1,desc:'Thiên vương vác đao quay diện rộng',level:'9x'},{name:'Thiên Vương Bản Nguyện',type:'Trấn Phái',priority:2,desc:'Trấn đại tăng damage',level:'6x'},{name:'Thiên Vương Đao',type:'Cơ bản',priority:3,desc:'Đao pháp cơ bản',level:'1x'},{name:'Tĩnh Tâm Quyết',type:'Hỗ trợ',priority:4,desc:'Tăng tốc đánh, rút ngắn giãn cách',level:'3x'},{name:'Khí Quán Trường Hồng',type:'Buff',priority:5,desc:'Tăng đánh trúng',level:'2x'}]",
    'nmkiem': "[{name:'Tam Nga Tề Tuyết',type:'DPS',priority:1,desc:'Kiếm 9x chém nhiều tia',level:'9x'},{name:'Phật Tâm Từ Bi',type:'Trấn Phái',priority:2,desc:'Trấn phái tăng kháng tất cả',level:'6x'},{name:'Nga My Kiếm Pháp',type:'Cơ bản',priority:3,desc:'Kiếm pháp cơ bản',level:'1x'},{name:'Lưu Thủy',type:'Hỗ trợ',priority:4,desc:'Vòng sáng chạy nhanh',level:'3x'},{name:'Phong Sương Toái Ảnh',type:'Ice',priority:5,desc:'Kiếm băng đóng băng',level:'9x'}]",
    'nmbuff': "[{name:'Phổ Độ Chúng Sinh',type:'Heal',priority:1,desc:'Hồi máu max bình cho cả xe',level:'9x'},{name:'Mộng Điệp',type:'Buff',priority:2,desc:'Hồi nội lực',level:'5x'},{name:'Lưu Thủy',type:'Buff',priority:3,desc:'Tăng tốc độ chạy mộc nhân',level:'3x'},{name:'Từ Hàng Phổ Độ',type:'Buff',priority:4,desc:'Hồi sinh liên tiếp',level:'4x'},{name:'Phật Tâm Từ Bi',type:'Trấn Phái',priority:5,desc:'Trấn phái kháng tất cả',level:'6x'}]",
    'tydao': "[{name:'Băng Tung Vô Ảnh',type:'DPS Nhồi',priority:1,desc:'Đao trượt xuyên mục tiêu 9x',level:'9x'},{name:'Băng Cốt Tuyết Tâm',type:'Trấn Phái',priority:2,desc:'Trấn phái tăng sát thương',level:'6x'},{name:'Thúy Yên Đao Pháp',type:'Cơ bản',priority:3,desc:'Đao cơ bản',level:'1x'},{name:'Hộ Thể Thần Công',type:'Buff',priority:4,desc:'Màng chắn sát thương',level:'4x'},{name:'Phong Tuyết',type:'Buff',priority:5,desc:'Thân pháp tăng né tránh',level:'6x'}]",
    'tysongdao': "[{name:'Băng Huyết Khinh Mạch',type:'AoE Băng',priority:1,desc:'Đẩy song đao đóng băng diện rộng',level:'9x'},{name:'Băng Cốt Tuyết Tâm',type:'Trấn Phái',priority:2,desc:'Trấn phái tăng sức mạnh Thủy',level:'6x'},{name:'Song Đao Pháp',type:'Cơ bản',priority:3,desc:'Cơ bản chém đôi',level:'1x'},{name:'Tuyết Ảnh',type:'Hỗ trợ',priority:4,desc:'Chạy trốn siêu tốc',level:'3x'},{name:'Hộ Thời Trận',type:'Aura',priority:5,desc:'Vòng sáng băng sát',level:'3x'}]",
    'vdkiem': "[{name:'Nhân Kiếm Hợp Nhất',type:'Xuyên Giáp',priority:1,desc:'Lướt kiếm siêu tốc đâm nát cọc',level:'9x'},{name:'Thái Cực Kiếm Pháp',type:'DPS',priority:2,desc:'Giật sét đánh xa',level:'9x'},{name:'Thái Cực Thần Công',type:'Trấn Phái',priority:3,desc:'Trấn phái tăng bỏ qua né',level:'6x'},{name:'Tọa Vọng Vô Ngã',type:'Buff Kiên',priority:4,desc:'Dùng nội lực đỡ sát thương',level:'3x'},{name:'Võ Đang Kiếm Pháp',type:'Cơ bản',priority:5,desc:'Cơ bản kiếm',level:'1x'}]",
    'vdkhi': "[{name:'Thiên Địa Vô Cực',type:'AoE Choáng',priority:1,desc:'Bão sấm sét làm choáng diện rộng',level:'9x'},{name:'Tọa Vọng Vô Ngã',type:'Buff',priority:2,desc:'Khiên mana cứng nhất game',level:'3x'},{name:'Thái Cực Thần Công',type:'Trấn Phái',priority:3,desc:'Trấn phái tăng tốc nội',level:'6x'},{name:'Vô Ngã Vô Kiếm',type:'DPS Nhồi',priority:4,desc:'Set sấm cực gắt dồn góc',level:'6x'},{name:'Côn Lôn Kiếm!',type:'Buff',priority:5,desc:'Hỗ trợ choáng',level:'1x'}]",
    'dmno': "[{name:'Bạo Vũ Lê Hoa',type:'DPS Góc',priority:1,desc:'Mưa nỏ tiễn sát thương khổng lồ',level:'9x'},{name:'Tâm Nhãn',type:'Trấn Phái',priority:2,desc:'Trấn phái Xuyên tâm, tăng chí mạng',level:'6x'},{name:'Độc Tật Lê',type:'Khoanh',priority:3,desc:'Cơ bản nỏ độc',level:'1x'},{name:'Ám Khí',type:'Basic',priority:4,desc:'Gia tăng sát thương cơ bản',level:'1x'},{name:'Độc Thích Cốt',type:'Aura',priority:5,desc:'Kháng Mộc và sát thương Mộc',level:'3x'}]",
    'dmtieu': "[{name:'Nhiếp Hồn Nguyệt Ảnh',type:'Giật Lag',priority:1,desc:'Phi tiêu găm liên tục không di chuyển nổi',level:'9x'},{name:'Tâm Nhãn',type:'Trấn Phái',priority:2,desc:'Trấn phái cực quan trọng',level:'6x'},{name:'Đoạt Hồn Tiêu',type:'Tầm xa',priority:3,desc:'Phi tiêu cơ bản',level:'1x'},{name:'Mãn Thiên Hoa Vũ',type:'Độc',priority:4,desc:'Phi tiêu dính độc siêu hạng',level:'5x'},{name:'Độc Thích Cốt',type:'Aura',priority:5,desc:'Aura tăng độc sát',level:'3x'}]",
    'dmdao': "[{name:'Tiểu Lý Phi Đao',type:'Sát Thủ',priority:1,desc:'Ném đao truy tung chí mạng',level:'9x'},{name:'Tâm Nhãn',type:'Trấn Phái',priority:2,desc:'Tăng chí mạng bạo kích',level:'6x'},{name:'Phi Đao Pháp',type:'Căn bản',priority:3,desc:'Phi đao cơ bản',level:'1x'},{name:'Xuyên Tâm Thích',type:'Choáng',priority:4,desc:'Chiêu độc rút máu nhanh',level:'3x'},{name:'Độc Thích Cốt',type:'Aura',priority:5,desc:'Tăng độc sát nội công',level:'3x'}]",
    'ndchuong': "[{name:'Vạn Cổ Thích Thiên',type:'Độc AoE',priority:1,desc:'Vòng nhện độc rút máu không ngừng',level:'9x'},{name:'Bách Độc Xuyên Tâm',type:'Trấn Phái',priority:2,desc:'Trấn phái hệ độc',level:'6x'},{name:'Vô Hình Cổ',type:'Aura Độc',priority:3,desc:'Aura giảm kháng độc mục tiêu',level:'3x'},{name:'Độc Xà Toản',type:'Cơ bản',priority:4,desc:'Phóng rắn cắn',level:'1x'},{name:'Âm Phong Thực Cốt',type:'Skill Khóa',priority:5,desc:'Khóa mục tiêu rút độc',level:'12x'}]",
    'nddao': "[{name:'Chu Cáp Não Thiên',type:'Xuyên Giáp',priority:1,desc:'Đao độc chém trên ngựa',level:'9x'},{name:'Bách Độc Xuyên Tâm',type:'Trấn Phái',priority:2,desc:'Trấn phái Ngũ độc',level:'6x'},{name:'Ngũ Độc Đao Pháp',type:'Cơ bản',priority:3,desc:'Cơ bản chém đao',level:'1x'},{name:'Vô Hình Cổ',type:'Aura Độc',priority:4,desc:'Giảm kháng độc mục tiêu',level:'3x'},{name:'Huyết Bạt Tiên',type:'Buff',priority:5,desc:'Buff máu bằng độc',level:'4x'}]",
    'cbchuong': "[{name:'Giáng Long Thập Bát',type:'Hỏa AoE',priority:1,desc:'Chưởng rồng lửa đốt cháy toàn màn hình',level:'9x'},{name:'Túy Điệp Cuồng Vũ',type:'Trấn Phái',priority:2,desc:'Trấn phái tăng di chuyển và sát thương hỏa',level:'6x'},{name:'Kháng Long Hữu Hối',type:'Chưởng rồng',priority:3,desc:'Phi rồng tầm xa',level:'5x'},{name:'Hàng Long Hữu Hối',type:'Cơ bản',priority:4,desc:'Chưởng cơ bản',level:'1x'},{name:'Hoạt Bất Lưu Thủ',type:'Buff di chuyển',priority:5,desc:'Chạy trốn luồn lách',level:'3x'}]",
    'cbbong': "[{name:'Đả Cẩu Trận Pháp',type:'Sát thương dội',priority:1,desc:'Gõ bổng đánh văng lan nhiều mục tiêu 9x',level:'9x'},{name:'Túy Điệp Cuồng Vũ',type:'Trấn Phái',priority:2,desc:'Trấn phái siêu tốc độ',level:'6x'},{name:'Cái Bang Bổng Pháp',type:'Cơ bản',priority:3,desc:'Cơ bản bổng pháp',level:'1x'},{name:'Tiêu Dao Công',type:'Nội Lực',priority:4,desc:'Buff tăng tấn công khi di chuyển',level:'3x'},{name:'Bổng Đả Ác Cẩu',type:'Choáng',priority:5,desc:'Khóa đối thủ tại chỗ',level:'4x'}]",
    'tndao': "[{name:'Hỏa Liên Phần Hoa',type:'Sóng Lửa',priority:1,desc:'Hút máu, tạo mảng hỏa liên kết',level:'9x'},{name:'Thiên Ma Giải Thể',type:'Trấn Phái',priority:2,desc:'Buff tà đạo hiến máu lấy sát thương',level:'6x'},{name:'Thiên Nhẫn Đao Pháp',type:'Cơ bản',priority:3,desc:'Cơ bản đao tà',level:'1x'},{name:'Ảo Ảnh Phi Hồ',type:'Buff né',priority:4,desc:'Tạo bóng né tránh',level:'3x'},{name:'Ma Âm Phệ Hồn',type:'Aura',priority:5,desc:'Mê hoặc giảm tấn công',level:'3x'}]",
    'tnthuong': "[{name:'Vân Long Kích',type:'Lướt Đâm',priority:1,desc:'Lướt thương để lại lửa diệt địch',level:'9x'},{name:'Thiên Ma Giải Thể',type:'Trấn Phái',priority:2,desc:'Bạo huyết tăng dame cực đại',level:'6x'},{name:'Thiên Nhẫn Thương',type:'Cơ bản',priority:3,desc:'Thương pháp căn bản',level:'1x'},{name:'Hấp Tinh Đại Pháp',type:'Aura',priority:4,desc:'Aura hút máu kẻ thù',level:'3x'},{name:'Phi Báo Trắc Trảo',type:'Đột kích',priority:5,desc:'Chiêu lướt áp sát',level:'4x'}]",
    'clkiem': "[{name:'Lôi Động Cửu Thiên',type:'Choáng Sét',priority:1,desc:'Trận sấm sét di động liên tục làm choáng',level:'9x'},{name:'Sương Ngạo Tuyết',type:'Trấn Phái',priority:2,desc:'Trấn phái tăng nội công hệ Thổ',level:'6x'},{name:'Côn Lôn Kiếm Pháp',type:'Cơ bản',priority:3,desc:'Cơ bản kiếm trận',level:'1x'},{name:'Mãn Thiên Phong Vũ',type:'Aura',priority:4,desc:'Vòng sáng kháng bão',level:'3x'},{name:'Khí Quán Thành Tâm',type:'Nội Buff',priority:5,desc:'Bơm nội sát thương',level:'5x'}]",
    'cldao': "[{name:'Ngạo Tuyết Tiêu Phong',type:'Wind AoE',priority:1,desc:'Trận cuồng phong nhồi damage diện rộng',level:'9x'},{name:'Sương Ngạo Tuyết',type:'Trấn Phái',priority:2,desc:'Trấn kiếm đao tăng kháng và sinh lực',level:'6x'},{name:'Côn Lôn Đao Pháp',type:'Cơ bản',priority:3,desc:'Đao pháp gió cuốn',level:'1x'},{name:'Hô Phong Hoán Vũ',type:'Aura',priority:4,desc:'Vòng sáng bão tố hỗ trợ',level:'3x'},{name:'Nhất Khí Hóa Tam Thanh',type:'Đa mục tiêu',priority:5,desc:'Khóa chân kẻ thụ',level:'4x'}]",
}

for char_id, skills_json_str in skills_data.items():
    # Find {id:'xxx', ... skills:[...]}
    # We use regex to replace skills array
    pattern = r"({id:'" + char_id + r"',.*?)skills:\[.*?\](.*?\})"
    
    # We need to be careful with dots crossing lines, but index.html uses single lines for each char.
    # The actual parsed block:
    def replace_skills(match):
        return match.group(1) + "skills:" + skills_json_str + match.group(2)
        
    content = re.sub(pattern, replace_skills, content, flags=re.IGNORECASE)

with open('index.html', 'w', encoding='utf-8') as f:
    f.write(content)

print("Updated perfectly.")
