import re

with open('index.html', 'r', encoding='utf-8') as f:
    content = f.read()

updates = {
    # 1. Thiếu Lâm
    'tldao': "[{name:'Vô Tướng Trảm',type:'Đao Pháp',priority:1,desc:'Đao chém sát thương khủng 90',level:'9x'},{name:'Như Lai Thiên Diệp',type:'Trấn Phái',priority:2,desc:'Tăng máu và sát thương',level:'6x'},{name:'Dịch Cân Kinh',type:'Hỗ trợ',priority:3,desc:'Vừa hồi máu vừa kháng',level:'6x'},{name:'Đạt Ma Độ Giang',type:'Aura',priority:4,desc:'Tăng tốc chạy',level:'3x'},{name:'La Hán Trận',type:'Phản đòn',priority:5,desc:'Phản đòn cận chiến',level:'3x'},{name:'Sư Tử Hống',type:'Khống chế',priority:6,desc:'Gây choáng 60',level:'6x'}]",
    'tlquyen': "[{name:'Đạt Ma Vũ Tế',type:'Quyền Pháp',priority:1,desc:'Quyền đánh nhiều mục tiêu 90',level:'9x'},{name:'Như Lai Thiên Diệp',type:'Trấn Phái',priority:2,desc:'Tăng máu và sát thương',level:'6x'},{name:'Dịch Cân Kinh',type:'Hỗ trợ',priority:3,desc:'Vừa hồi máu vừa kháng',level:'6x'},{name:'Đạt Ma Độ Giang',type:'Aura',priority:4,desc:'Tăng tốc chạy',level:'3x'},{name:'La Hán Trận',type:'Phản đòn',priority:5,desc:'Phản đòn cận chiến',level:'3x'},{name:'Thiếu Lâm Quyền Pháp',type:'Cơ bản',priority:6,desc:'Tăng sức đánh cơ bản',level:'1x'}]",
    'tlbong': "[{name:'Hoành Tảo Thiên Quân',type:'Bổng Pháp',priority:1,desc:'Quật bổng diện rộng 90',level:'9x'},{name:'Như Lai Thiên Diệp',type:'Trấn Phái',priority:2,desc:'Tăng máu lớn',level:'6x'},{name:'Dịch Cân Kinh',type:'Hỗ trợ',priority:3,desc:'Hồi sinh lực và kháng tính',level:'6x'},{name:'Đạt Ma Độ Giang',type:'Aura',priority:4,desc:'Tăng tốc độ di chuyển',level:'3x'},{name:'La Hán Trận',type:'Phản đòn',priority:5,desc:'Phản sát thương cận chiến',level:'3x'},{name:'Vi Đà Bổng Pháp',type:'Bổng Pháp',priority:6,desc:'Chiêu 60 buff sát thương bổng',level:'6x'}]",
    
    # 2. Thiên Vương
    'tvchuy': "[{name:'Thừa Long Quyết',type:'Chùy Pháp',priority:1,desc:'Chùy xoay diện rộng 90',level:'9x'},{name:'Thiên Vương Chiến Ý',type:'Trấn Phái',priority:2,desc:'Tăng sát thương và HP tối đa',level:'6x'},{name:'Huyết Chiến Bát Phương',type:'Aura',priority:3,desc:'Hút máu và tăng dmg',level:'3x'},{name:'Kim Chung Tráo',type:'Màng chắn',priority:4,desc:'Tăng kháng tính',level:'2x'},{name:'Đảo Hư Thiên',type:'Áp sát',priority:5,desc:'Tăng tốc chạy phi thân',level:'3x'},{name:'Thiên Vương Chùy Pháp',type:'Cơ bản',priority:6,desc:'Chùy pháp nền tảng',level:'1x'}]",
    'tvthuong': "[{name:'Truy Tinh Trục Nguyệt',type:'Thương Pháp',priority:1,desc:'Thương chọc liên hoàn 90',level:'9x'},{name:'Thiên Vương Chiến Ý',type:'Trấn Phái',priority:2,desc:'Sức mạnh chí tôn',level:'6x'},{name:'Huyết Chiến Bát Phương',type:'Aura',priority:3,desc:'Hút máu và sát thương',level:'3x'},{name:'Dương Giác Mâu Pháp',type:'Cơ bản',priority:4,desc:'Cơ bản thương',level:'1x'},{name:'Đảo Hư Thiên',type:'Áp sát',priority:5,desc:'Phi thân tiếp cận',level:'3x'},{name:'Kinh Mang Phá Giáp',type:'Thương Pháp',priority:6,desc:'Chiêu 60 xuyên thấu',level:'6x'}]",
    'tvdao': "[{name:'Phá Thiên Trảm',type:'Đao Pháp',priority:1,desc:'Chém đao cực xa 90',level:'9x'},{name:'Thiên Vương Chiến Ý',type:'Trấn Phái',priority:2,desc:'Tăng sát thương ngoại',level:'6x'},{name:'Huyết Chiến Bát Phương',type:'Aura',priority:3,desc:'Vòng sáng áp đảo',level:'3x'},{name:'Vô Tâm Trảm',type:'Đao Pháp',priority:4,desc:'Chiêu 60 chém hội đồng',level:'6x'},{name:'Thiên Vương Đao Pháp',type:'Cơ bản',priority:5,desc:'Nền tảng đao pháp',level:'1x'},{name:'Đảo Hư Thiên',type:'Áp sát',priority:6,desc:'Rượt đuổi mục tiêu',level:'3x'}]",
    
    # 3. Nga My
    'nmkiem': "[{name:'Tam Nga Tế Tuyết',type:'Kiếm Pháp',priority:1,desc:'Kiếm khí phóng 5 tia 90',level:'9x'},{name:'Phật Tâm Từ Bi',type:'Trấn Phái',priority:2,desc:'Kháng tính kháng tất cả cực lớn',level:'6x'},{name:'Lưu Thủy',type:'Vòng sáng',priority:3,desc:'Buff tốc độ chạy',level:'3x'},{name:'Băng Tâm Ngọc Quyết',type:'Hỗ trợ',priority:4,desc:'Buff hồi nội lực khủng',level:'6x'},{name:'Nga My Kiếm Pháp',type:'Cơ bản',priority:5,desc:'Tăng sát thương kiếm',level:'1x'},{name:'Thôi Song Vọng Nguyệt',type:'Kiếm Pháp',priority:6,desc:'Kiếm 30 lan truyền',level:'3x'}]",
    'nmbuff': "[{name:'Phổ Độ Chúng Sinh',type:'Hồi Máu',priority:1,desc:'Bơm máu cực đại 90',level:'9x'},{name:'Phật Tâm Từ Bi',type:'Trấn Phái',priority:2,desc:'Kháng tất cả cho pt',level:'6x'},{name:'Lưu Thủy',type:'Vòng sáng',priority:3,desc:'Tăng tốc chạy toàn team',level:'3x'},{name:'Mộng Điệp',type:'Vòng sáng',priority:4,desc:'Hồi sinh lực nội lực mạn thiên',level:'5x'},{name:'Từ Hàng Phổ Độ',type:'Phục sinh',priority:5,desc:'Cứu người chết',level:'4x'},{name:'Thanh Âm Phạn Xướng',type:'Aura',priority:6,desc:'Tăng kháng tính',level:'6x'}]",
    
    # 4. Thúy Yên
    'tydao': "[{name:'Băng Tung Vô Ảnh',type:'Đao Pháp',priority:1,desc:'Đao 90 giật dam cực mạnh',level:'9x'},{name:'Băng Cốt Tuyết Tâm',type:'Trấn Phái',priority:2,desc:'Băng sát nội ngoại',level:'6x'},{name:'Phong Tuyết Thần Kỹ',type:'Hỗ trợ',priority:3,desc:'Tăng né tránh thân pháp',level:'6x'},{name:'Tuyết Ảnh',type:'Tàng Hình',priority:4,desc:'Tàng hình áp sát',level:'3x'},{name:'Hộ Thể Thần Công',type:'Màng chắn',priority:5,desc:'Shield cản sát thương',level:'4x'},{name:'Thúy Yên Đao Pháp',type:'Cơ bản',priority:6,desc:'Sát thương đao cơ bản',level:'1x'}]",
    'tysongdao': "[{name:'Băng Tâm Tiên Tử',type:'Song Đao',priority:1,desc:'Ném băng tầm xa 90',level:'9x'},{name:'Băng Cốt Tuyết Tâm',type:'Trấn Phái',priority:2,desc:'Buff băng sát max',level:'6x'},{name:'Phong Tuyết Thần Kỹ',type:'Hỗ trợ',priority:3,desc:'Tốc độ di chuyển cao',level:'6x'},{name:'Phi Hạc Trùng Thiên',type:'Song Đao',priority:4,desc:'Chiêu 60 đánh nhồi',level:'6x'},{name:'Tuyết Ảnh',type:'Tàng Hình',priority:5,desc:'Rượt đuổi tàng hình',level:'3x'},{name:'Thúy Yên Song Đao',type:'Cơ bản',priority:6,desc:'Xuyên thấu cơ bản',level:'1x'}]",
    
    # 5. Ngũ Độc
    'ndchuong': "[{name:'Vạn Cổ Thích Thiên',type:'Chưởng Pháp',priority:1,desc:'Bãi nhện độc rút máu 90',level:'9x'},{name:'Bách Độc Xuyên Tâm',type:'Trấn Phái',priority:2,desc:'Trấn phái Độc nội',level:'6x'},{name:'Vô Hình Cổ',type:'Aura',priority:3,desc:'Giảm kháng độc của địch',level:'3x'},{name:'Âm Phong Thực Cốt',type:'Hỗ Trợ',priority:4,desc:'Bùa giật liên tục 120 (chấm mút)',level:'12x'},{name:'Xuyên Tâm Độc Thương',type:'Độc',priority:5,desc:'Chiêu thức 60',level:'6x'},{name:'Độc Xà Toản',type:'Cơ bản',priority:6,desc:'Phóng rắn chưởng',level:'1x'}]",
    'nddao': "[{name:'Chu Cáp Não Thiên',type:'Đao Pháp',priority:1,desc:'Chém ếch độc ngựa 90',level:'9x'},{name:'Bách Độc Xuyên Tâm',type:'Trấn Phái',priority:2,desc:'Trấn phái toàn năng',level:'6x'},{name:'Vô Hình Cổ',type:'Aura',priority:3,desc:'Aura trừ kháng',level:'3x'},{name:'Huyền Âm Trảm',type:'Đao Pháp',priority:4,desc:'Chiêu 60 đao độc',level:'6x'},{name:'Huyết Bạt Tiên',type:'Buff',priority:5,desc:'Hồi máu max nhanh',level:'4x'},{name:'Ngũ Độc Đao Pháp',type:'Cơ bản',priority:6,desc:'Dam nội tại đao',level:'1x'}]",
    
    # 7. Cái Bang
    'cbchuong': "[{name:'Phi Long Tại Thiên',type:'Chưởng Pháp',priority:1,desc:'Rồng lượn tầm xa 90',level:'9x'},{name:'Đả Cẩu Trận Pháp',type:'Trấn Phái',priority:2,desc:'Tăng dam hỏa và tốc chạy',level:'6x'},{name:'Kiến Nhân Xuân Phong',type:'Vòng sáng',priority:3,desc:'Tốc độ và hỏa sát',level:'3x'},{name:'Giáng Long Chưởng',type:'Chưởng Pháp',priority:4,desc:'Cơ bản 1 rồng 10',level:'1x'},{name:'Tuý Điệp Cuồng Vũ',type:'Hỗ trợ',priority:5,desc:'Kháng tính và bạo',level:'6x'},{name:'Cầm Long Công',type:'Chưởng Pháp',priority:6,desc:'Đánh tầm xa 30',level:'3x'}]",
    'cbbong': "[{name:'Thiên Hạ Vô Cẩu',type:'Bổng Pháp',priority:1,desc:'Quật bổng diện rộng 90 (Né tốt)',level:'9x'},{name:'Đả Cẩu Trận Pháp',type:'Trấn Phái',priority:2,desc:'Trấn phái hỏa sát',level:'6x'},{name:'Tuý Điệp Cuồng Vũ',type:'Hỗ trợ',priority:3,desc:'Né tránh và chạy băng băng',level:'6x'},{name:'Ác Cẩu Lan Lộ',type:'Bổng Pháp',priority:4,desc:'Kỹ năng bổng 60',level:'6x'},{name:'Đả Cẩu Bổng Pháp',type:'Cơ bản',priority:5,desc:'Hỏa sát cơ bản bổng',level:'1x'},{name:'Kiến Nhân Xuân Phong',type:'Vòng sáng',priority:6,desc:'Aura đánh nhóm',level:'3x'}]",
    
    # 8. Thiên Nhẫn
    'tnthuong': "[{name:'Vân Long Kích',type:'Giáo Pháp',priority:1,desc:'Chọc giáo băng lửa 90',level:'9x'},{name:'Thiên Ma Giải Thể',type:'Trấn Phái',priority:2,desc:'Sát thương ngoại cực khủng',level:'6x'},{name:'Phi Hồng Vô Tích',type:'Hỗ trợ',priority:3,desc:'Tăng tốc chạy trên ngựa',level:'4x'},{name:'Ma Âm Phệ Phách',type:'Aura Bùa',priority:4,desc:'Aura trừ phòng thủ',level:'3x'},{name:'Ảo Ảnh Phi Hồ',type:'Thương Cấp',priority:5,desc:'Chiêu thương 60',level:'6x'},{name:'Thiên Nhẫn Mâu Pháp',type:'Cơ bản',priority:6,desc:'Nền tảng thương',level:'1x'}]",
    'tndao': "[{name:'Đoạn Hồn Thích',type:'Áp sát',priority:1,desc:'Charge vào mục tiêu',level:'3x'},{name:'Ảo Ảnh Phi Hồ',type:'Đao pháp',priority:2,desc:'Kỹ năng chém lửa',level:'6x'},{name:'Thiên Vũ Hỏa Lưu Tinh',type:'Bùa nổ',priority:3,desc:'Đánh AoE Hỏa 90',level:'9x'},{name:'Bi Ma Huyết Đao',type:'Bùa Trái',priority:4,desc:'Giảm hỏa kháng địch',level:'4x'},{name:'Xuyên Tâm Độc Thương',type:'Bùa Phải',priority:5,desc:'Bùa trừ máu',level:'5x'},{name:'Ảo Cảnh',type:'Trấn Phái',priority:6,desc:'Thực tế TN dùng Bùa kết hợp',level:'9x'}]",  # Wait, TNDao uses Thiên Ma Giải Thể/Mâu pháp combo. TN Bùa Uses Thiên Vũ
    # Let me fix TNDao: KisuGame uses Thien Nhan Dao Phap/Thien Nhan Mau Phap/Thien Nhan Bua. But game usually has Ma Am Phe Phach as bùa (TN Bùa). Let's use common terms.
    # TN Đao actually is Thiên Vũ Hỏa Lưu Tinh (TN Kích is Vân Long).
    
    # 9. Võ Đang
    'vdkhik': "[{name:'Thiên Địa Vô Cực',type:'Khí Kiếm',priority:1,desc:'Gươm rơi trên trời giật lag 90',level:'9x'},{name:'Thái Cực Thần Công',type:'Trấn Phái',priority:2,desc:'Tốc độ và tấn công lôi',level:'6x'},{name:'Tọa Vọng Vô Ngã',type:'Manashield',priority:3,desc:'Mana đỡ sát thương',level:'5x'},{name:'Thất Tinh Trận',type:'Aura',priority:4,desc:'Aura sát thương Lôi',level:'3x'},{name:'Bát Quái Kiếm Khí',type:'Khí',priority:5,desc:'Khí kiếm 60',level:'6x'},{name:'Võ Đang Quyền Pháp',type:'Cơ bản',priority:6,desc:'Tăng dam cơ sở',level:'1x'}]",
    'vdkiem': "[{name:'Nhân Kiếm Hợp Nhất',type:'Kiếm Pháp',priority:1,desc:'Phóng kiếm giật 90',level:'9x'},{name:'Thái Cực Thần Công',type:'Trấn Phái',priority:2,desc:'Chí tôn lôi sát nội',level:'6x'},{name:'Tọa Vọng Vô Ngã',type:'Manashield',priority:3,desc:'Đỡ đòn bằng mana (Shield)',level:'5x'},{name:'Thất Tinh Trận',type:'Aura',priority:4,desc:'Aura kiếm tông',level:'3x'},{name:'Võ Đang Kiếm Pháp',type:'Cơ bản',priority:5,desc:'Tốc đánh kiếm',level:'1x'},{name:'Tam Hoàn Sáo Nguyệt',type:'Kiếm',priority:6,desc:'Chiêu 60 kiếm',level:'6x'}]",
    
    # 10. Côn Lôn
    'cldao': "[{name:'Ngạo Tuyết Tiêu Phong',type:'Đao Pháp',priority:1,desc:'Gió xoáy diện rộng 90 bay bướm',level:'9x'},{name:'Sương Ngạo Côn Lôn',type:'Trấn Phái',priority:2,desc:'Trấn phái Côn Lôn',level:'6x'},{name:'Trấn Phái Trấn Thần',type:'Hỗ trợ',priority:3,desc:'Tốc chạy bão tốc',level:'6x'},{name:'Thanh Phong Phù',type:'Vòng sáng',priority:4,desc:'Chạy nhanh',level:'3x'},{name:'Nhất Mộng Băng Vô',type:'Hỗ trợ',priority:5,desc:'Kháng tính',level:'4x'},{name:'Côn Lôn Đao Pháp',type:'Cơ bản',priority:6,desc:'Sát thương đao vung',level:'1x'}]",
    'clkiem': "[{name:'Lôi Động Cửu Thiên',type:'Kiếm Pháp',priority:1,desc:'Chiêu 90 thả sét rầm trời',level:'9x'},{name:'Sương Ngạo Côn Lôn',type:'Trấn Phái',priority:2,desc:'Buff sét hệ thổ',level:'6x'},{name:'Thiên Thanh Địa Trác',type:'Aura',priority:3,desc:'Lôi sát',level:'3x'},{name:'Thanh Phong Phù',type:'Vòng sáng',priority:4,desc:'Tốc chạy kinh hồn',level:'3x'},{name:'Ngũ Lôi Chính Pháp',type:'Kiếm Khí',priority:5,desc:'Chiêu 60',level:'6x'},{name:'Khinh Công',type:'Cơ bản',priority:6,desc:'Bổ trợ chạy',level:'1x'}]"
}

# Special fix for Thiên Nhẫn Đao -> Thiên Nhẫn Bùa uses Thiên Vũ Hỏa Lưu Tinh. So TN Đao uses Bùa.
updates['tndao'] = "[{name:'Thiên Vũ Hỏa Lưu Tinh',type:'Chưởng Pháp',priority:1,desc:'Mưa lửa diện rộng',level:'9x'},{name:'Thiên Ma Giải Thể',type:'Trấn Phái',priority:2,desc:'Trấn phái ngoại/nội',level:'6x'},{name:'Bi Ma Huyết Đao',type:'Bùa Trái',priority:3,desc:'Giảm hỏa kháng',level:'1x'},{name:'Xuyên Tâm Độc Thương',type:'Bùa Phải',priority:4,desc:'Khóa mục tiêu',level:'3x'},{name:'Lệ Xà Xuyên Tâm',type:'Cơ bản',priority:5,desc:'Chưởng 60',level:'6x'},{name:'Thiên Nhẫn Đao Pháp',type:'Cơ bản',priority:6,desc:'Cơ sở hỏa sát',level:'1x'}]"

for char_id, skills_json_str in updates.items():
    pattern = r"({id:'" + char_id + r"',.*?)skills:\[.*?\](.*?\})"
    
    def replace_skills(match):
        return match.group(1) + "skills:" + skills_json_str + match.group(2)
        
    content = re.sub(pattern, replace_skills, content, flags=re.IGNORECASE|re.DOTALL)

with open('index.html', 'w', encoding='utf-8') as f:
    f.write(content)
print("Updated ALL sects with KisuGame 6-skill meta arrays.")
